name: 'Check Code Scanning Status'
description: 'Check the status of Code Scanning analysis'
branding:
  icon: "alert-triangle"
  color: "red"
inputs:
  token:
    description: 'GitHub token'
    required: true
  pr_number:
    description: 'Pull request number'
    required: true
  repo:
    description: 'Repository'
    required: true
runs:
  using: 'composite'
  steps:
    - run: chmod +x ${{ github.action_path }}/src/run.sh
      shell: bash
    - run: ${{ github.action_path }}/src/run.sh "${{ inputs.token }}" "${{ inputs.pr_number }}" "${{ inputs.repo }}"
      shell: bash
